# Generated by Django 4.0.4 on 2022-05-26 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_id', models.IntegerField(blank=True, null=True)),
                ('request_type_id', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('created_on', models.DateTimeField(blank=True, null=True)),
                ('type', models.IntegerField()),
                ('code', models.CharField(max_length=255)),
                ('email', models.CharField(db_collation='utf8_general_ci', max_length=255)),
                ('send_mail_on_create', models.IntegerField()),
                ('source_email', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=255, null=True)),
                ('source_name', models.CharField(db_collation='utf8_general_ci', max_length=255)),
                ('referral_subject', models.CharField(blank=True, max_length=255, null=True)),
                ('referral_text', models.TextField(blank=True, null=True)),
                ('success_message', models.TextField()),
                ('design', models.IntegerField()),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('subtitle', models.TextField(blank=True, null=True)),
                ('text_button', models.CharField(max_length=255)),
                ('double_opt_in', models.CharField(db_collation='utf8_general_ci', max_length=255)),
                ('double_opt_in_url', models.CharField(blank=True, max_length=255, null=True)),
                ('generate_lead', models.IntegerField()),
                ('limit', models.IntegerField(blank=True, null=True)),
                ('status', models.IntegerField()),
                ('enable_captcha', models.IntegerField()),
                ('enable_trigger', models.IntegerField()),
                ('enable_lead_alerts', models.IntegerField()),
                ('image_header', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=255, null=True)),
                ('custom_inactive_msg', models.TextField(blank=True, null=True)),
                ('custom_limit_msg', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'action',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ActionMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_key', models.CharField(max_length=255)),
                ('meta_value', models.TextField()),
            ],
            options={
                'db_table': 'action_meta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('working_time', models.IntegerField(blank=True, null=True)),
                ('request_time', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'area',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AreaListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'area_listing',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Blacklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(db_collation='utf8_general_ci', max_length=255, unique=True)),
                ('bounced', models.IntegerField()),
                ('unsubscribed', models.IntegerField()),
                ('unsubscribed_on', models.DateTimeField()),
                ('unsubscribe_reason', models.IntegerField(blank=True, null=True)),
                ('unsubscribe_reason_text', models.CharField(blank=True, max_length=255, null=True)),
                ('spam', models.IntegerField()),
                ('manually', models.IntegerField()),
            ],
            options={
                'db_table': 'blacklist',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('html', models.TextField()),
                ('text', models.TextField()),
                ('from_name', models.CharField(max_length=255)),
                ('from_email', models.CharField(db_collation='utf8_general_ci', max_length=255)),
                ('reply_to', models.CharField(max_length=255)),
                ('listing_names', models.CharField(blank=True, max_length=1024, null=True)),
                ('status', models.IntegerField()),
                ('sent', models.IntegerField()),
                ('opened', models.IntegerField()),
                ('bounced', models.IntegerField()),
                ('clicked', models.IntegerField()),
                ('unsubscribed', models.IntegerField()),
                ('spam', models.IntegerField()),
                ('created_on', models.DateTimeField(blank=True, null=True)),
                ('updated_on', models.DateTimeField(blank=True, null=True)),
                ('sent_date', models.DateTimeField(blank=True, null=True)),
                ('send_date', models.DateTimeField(blank=True, null=True)),
                ('step', models.IntegerField(blank=True, null=True)),
                ('editor', models.IntegerField(blank=True, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('metadata', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'campaign',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CampaignFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'campaign_filter',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CampaignListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'campaign_listing',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CampaignSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(db_collation='utf8_general_ci', max_length=255)),
                ('sent', models.IntegerField()),
                ('bounced', models.IntegerField()),
                ('opened', models.IntegerField()),
                ('opened_date', models.DateTimeField(blank=True, null=True)),
                ('clicked', models.IntegerField()),
                ('unsubscribed', models.IntegerField()),
                ('spam', models.IntegerField()),
                ('country', models.CharField(blank=True, max_length=10, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('client_os', models.CharField(blank=True, max_length=100, null=True)),
                ('client_device_type', models.CharField(blank=True, max_length=100, null=True)),
                ('client_name', models.CharField(blank=True, max_length=100, null=True)),
                ('client_type', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'campaign_subscriber',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CampaignSubscriberUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clicked_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'campaign_subscriber_url',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CampaignUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=1000)),
                ('clicked', models.IntegerField()),
            ],
            options={
                'db_table': 'campaign_url',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_on', models.DateTimeField()),
                ('active', models.IntegerField()),
                ('type', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'comment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=255, null=True, unique=True)),
                ('account_id', models.IntegerField()),
                ('email', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=255, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_source', models.IntegerField(blank=True, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_source', models.IntegerField(blank=True, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('firstname', models.CharField(blank=True, max_length=255, null=True)),
                ('lastname', models.CharField(blank=True, max_length=255, null=True)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('region', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('is_blacklisted', models.IntegerField(blank=True, default=0)),
                ('bounced', models.IntegerField(blank=True, default=0)),
                ('unsubscribed', models.IntegerField(blank=True, default=0)),
                ('unsubscribed_on', models.DateTimeField(blank=True, null=True)),
                ('unsubscribe_reason', models.IntegerField(blank=True, null=True)),
                ('unsubscribe_reason_text', models.CharField(blank=True, max_length=255, null=True)),
                ('manually', models.IntegerField(blank=True, default=0)),
                ('spam', models.IntegerField(blank=True, default=0)),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
                ('score', models.IntegerField(blank=True, default=0)),
                ('comments', models.TextField(blank=True, null=True)),
                ('flag', models.IntegerField(blank=True, default=0)),
                ('fields', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'contact',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ContactData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=1024)),
            ],
            options={
                'db_table': 'contact_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ContactField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('placeholder', models.CharField(max_length=255)),
                ('options', models.JSONField(blank=True, null=True)),
                ('type', models.IntegerField()),
                ('default_value', models.CharField(blank=True, max_length=255, null=True)),
                ('position', models.IntegerField()),
                ('enable_crm', models.IntegerField()),
                ('enable_view', models.IntegerField()),
                ('fixed', models.IntegerField()),
            ],
            options={
                'db_table': 'contact_field',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ContactTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField()),
            ],
            options={
                'db_table': 'contact_tag',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('origin', models.CharField(blank=True, max_length=255, null=True)),
                ('is_api', models.IntegerField()),
            ],
            options={
                'db_table': 'event',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EventField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.IntegerField()),
            ],
            options={
                'db_table': 'event_field',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FieldData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField()),
                ('verified', models.IntegerField()),
                ('trigger_email', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=255, null=True)),
                ('traffic_type', models.CharField(blank=True, max_length=255, null=True)),
                ('traffic_source', models.CharField(blank=True, max_length=255, null=True)),
                ('traffic_medium', models.CharField(blank=True, max_length=255, null=True)),
                ('session_pages', models.IntegerField(blank=True, null=True)),
                ('current_page', models.CharField(blank=True, db_collation='utf8mb4_0900_ai_ci', max_length=2000, null=True)),
                ('client_device_type', models.CharField(blank=True, max_length=255, null=True)),
                ('client_os', models.CharField(blank=True, max_length=255, null=True)),
                ('client_name', models.CharField(blank=True, max_length=255, null=True)),
                ('client_ip', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'field_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FieldDataValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
            ],
            options={
                'db_table': 'field_data_values',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FieldOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=255)),
                ('field_order', models.IntegerField()),
            ],
            options={
                'db_table': 'field_option',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('filter', models.CharField(max_length=1024)),
                ('operator_type', models.IntegerField()),
                ('filter_json', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'filter',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FormData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField()),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(db_collation='utf8_general_ci', max_length=255)),
                ('referred_by', models.CharField(blank=True, max_length=255, null=True)),
                ('data', models.TextField()),
            ],
            options={
                'db_table': 'form_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_type', models.IntegerField()),
                ('short_name', models.CharField(db_collation='utf8_general_ci', max_length=255)),
                ('field_name', models.CharField(max_length=1024)),
                ('field_order', models.IntegerField()),
                ('unique', models.IntegerField()),
                ('is_required', models.IntegerField()),
                ('is_conditional', models.IntegerField()),
                ('image_name', models.CharField(blank=True, max_length=1024, null=True)),
                ('json_condition', models.JSONField(blank=True, null=True)),
                ('validations', models.CharField(blank=True, max_length=512, null=True)),
            ],
            options={
                'db_table': 'form_field',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('fields', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cc_user', models.IntegerField(blank=True, null=True)),
                ('updated_on', models.DateTimeField(blank=True, null=True)),
                ('created_on', models.DateTimeField(blank=True, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('data', models.TextField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('first_email_sent', models.IntegerField()),
                ('lead_time', models.FloatField(blank=True, null=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('type_time', models.IntegerField(blank=True, null=True)),
                ('closed_on', models.DateField(blank=True, null=True)),
                ('status_0', models.IntegerField(db_column='status')),
                ('trace', models.JSONField(blank=True, null=True)),
                ('followers', models.JSONField(blank=True, null=True)),
                ('is_contacted', models.IntegerField(blank=True, null=True)),
                ('contacted_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'lead',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LeadSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'lead_skill',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_on', models.DateTimeField(blank=True, null=True)),
                ('unsubscribe_external_url', models.CharField(blank=True, max_length=2048, null=True)),
                ('invite_from', models.CharField(blank=True, max_length=255, null=True)),
                ('invite_from_email', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=255, null=True)),
                ('invite_subject', models.CharField(blank=True, max_length=255, null=True)),
                ('invite_message', models.TextField(blank=True, null=True)),
                ('flag', models.IntegerField()),
            ],
            options={
                'db_table': 'listing',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateTimeField()),
                ('element_id', models.IntegerField(blank=True, null=True)),
                ('json_fields', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('value', models.CharField(max_length=2048)),
            ],
            options={
                'db_table': 'option',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RequestType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('working_time', models.IntegerField(blank=True, null=True)),
                ('request_time', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'request_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'role',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RoleCapability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'role_capability',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('rule_trigger', models.IntegerField()),
                ('field_id', models.IntegerField(blank=True, null=True)),
                ('field_value', models.CharField(blank=True, max_length=255, null=True)),
                ('rule_trigger_value', models.IntegerField()),
                ('status', models.IntegerField()),
            ],
            options={
                'db_table': 'rule',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RuleContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('email', models.CharField(db_collation='utf8_general_ci', max_length=255)),
                ('start_time', models.DateTimeField()),
                ('added_time', models.DateTimeField()),
                ('status', models.IntegerField()),
            ],
            options={
                'db_table': 'rule_contact',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RuleMail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('account_id', models.IntegerField()),
                ('subject', models.CharField(max_length=255)),
                ('html', models.TextField(blank=True, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('from_name', models.CharField(max_length=255)),
                ('from_email', models.CharField(max_length=255)),
                ('reply_to', models.CharField(max_length=255)),
                ('template_id', models.IntegerField(blank=True, null=True)),
                ('created_on', models.DateTimeField(blank=True, null=True)),
                ('updated_on', models.DateTimeField(blank=True, null=True)),
                ('editor', models.IntegerField(blank=True, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('metadata', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rule_mail',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RuleStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.IntegerField()),
                ('value', models.IntegerField(blank=True, null=True)),
                ('wait_time_unit', models.IntegerField()),
                ('wait_time_value', models.IntegerField()),
                ('position', models.IntegerField()),
            ],
            options={
                'db_table': 'rule_stage',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.IntegerField()),
                ('value', models.IntegerField()),
                ('recurring', models.IntegerField()),
                ('max', models.IntegerField()),
            ],
            options={
                'db_table': 'score',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ScoreLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField()),
                ('value', models.IntegerField()),
            ],
            options={
                'db_table': 'score_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'skill',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.IntegerField()),
            ],
            options={
                'db_table': 'source',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('start', models.IntegerField(blank=True, null=True)),
                ('end', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'status',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(blank=True, null=True)),
                ('updated_on', models.DateTimeField(blank=True, null=True)),
                ('unsubscribed_on', models.DateTimeField(blank=True, null=True)),
                ('bounced', models.IntegerField()),
                ('unsubscribed', models.IntegerField()),
                ('unsubscribe_reason', models.IntegerField(blank=True, null=True)),
                ('unsubscribe_reason_text', models.CharField(blank=True, max_length=255, null=True)),
                ('spam', models.IntegerField()),
                ('manually', models.IntegerField()),
            ],
            options={
                'db_table': 'subscriber',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_on', models.DateTimeField()),
            ],
            options={
                'db_table': 'tag',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblMigration',
            fields=[
                ('version', models.CharField(max_length=180, primary_key=True, serialize=False)),
                ('apply_time', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_migration',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('html', models.TextField(blank=True, db_collation='utf8mb4_0900_ai_ci', null=True)),
                ('editor', models.IntegerField()),
                ('body', models.TextField(blank=True, null=True)),
                ('metadata', models.TextField(blank=True, null=True)),
                ('preview', models.TextField(blank=True, db_collation='utf8mb4_0900_ai_ci', null=True)),
            ],
            options={
                'db_table': 'template',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TicketField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_type', models.IntegerField()),
                ('options', models.JSONField(blank=True, null=True)),
                ('type', models.IntegerField(blank=True, null=True)),
                ('close_required', models.IntegerField()),
                ('create_required', models.IntegerField()),
                ('user_required', models.IntegerField()),
                ('extern_name', models.CharField(blank=True, max_length=255, null=True)),
                ('intern_name', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(max_length=255)),
                ('order', models.IntegerField()),
                ('field_text', models.CharField(blank=True, max_length=2000, null=True)),
                ('ticket_field_option_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ticket_field',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TicketFieldRestriction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField()),
                ('request_type_id', models.IntegerField(blank=True, null=True)),
                ('option', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'ticket_field_restriction',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TicketFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=1024)),
            ],
            options={
                'db_table': 'ticket_field_value',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TicketTrigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField()),
                ('data_type', models.IntegerField(blank=True, null=True)),
                ('value', models.IntegerField()),
                ('subvalue', models.IntegerField(blank=True, null=True)),
                ('subvalue_data', models.CharField(blank=True, max_length=255, null=True)),
                ('action', models.IntegerField()),
                ('action_value', models.IntegerField()),
                ('request_time', models.FloatField(blank=True, null=True)),
                ('working_time', models.IntegerField(blank=True, null=True)),
                ('text_field', models.TextField(blank=True, null=True)),
                ('enable_asign_trigger', models.IntegerField(blank=True, null=True)),
                ('field_read_id', models.IntegerField(blank=True, null=True)),
                ('ticket_field_write_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ticket_trigger',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_overseer', models.IntegerField()),
                ('crm_user', models.IntegerField()),
            ],
            options={
                'db_table': 'user_role',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserRoleArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'user_role_area',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserRoleSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'user_role_skill',
                'managed': False,
            },
        ),
    ]
