# Generated by Django 4.0.4 on 2022-05-16 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userrole',
            options={'managed': True},
        ),
    ]
