# Generated by Django 4.0.4 on 2022-05-26 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_collation='latin1_swedish_ci', max_length=255)),
                ('status', models.IntegerField()),
                ('bulker', models.IntegerField()),
                ('auto', models.IntegerField()),
                ('domain', models.CharField(db_collation='latin1_swedish_ci', max_length=100, unique=True)),
                ('api_token', models.CharField(db_collation='latin1_swedish_ci', max_length=255)),
                ('api_secret', models.CharField(db_collation='latin1_swedish_ci', max_length=255)),
                ('descuento', models.FloatField(blank=True, null=True)),
                ('email_account', models.CharField(blank=True, max_length=255, null=True)),
                ('external_id', models.CharField(blank=True, max_length=255, null=True)),
                ('enabled', models.IntegerField()),
                ('disabled_reason', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'account',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AccountPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'account_plan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AccountUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'account_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Capability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'capability',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('active', models.IntegerField()),
            ],
            options={
                'db_table': 'module',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ModulePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'module_plan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_collation='latin1_swedish_ci', max_length=255)),
                ('max_contacts', models.IntegerField(blank=True, null=True)),
                ('max_users_crm', models.IntegerField(blank=True, null=True)),
                ('max_forms', models.IntegerField(blank=True, null=True)),
                ('price', models.FloatField()),
                ('api_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'plan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(db_collation='latin1_swedish_ci', max_length=100, unique=True)),
                ('password', models.CharField(db_collation='latin1_swedish_ci', max_length=100)),
                ('firstname', models.CharField(db_collation='latin1_swedish_ci', max_length=255)),
                ('lastname', models.CharField(db_collation='latin1_swedish_ci', max_length=255)),
                ('status', models.IntegerField()),
                ('created', models.DateTimeField()),
                ('lastvisit', models.DateTimeField(blank=True, null=True)),
                ('token', models.CharField(blank=True, db_collation='latin1_swedish_ci', max_length=255, null=True)),
                ('token_created', models.DateTimeField(blank=True, null=True)),
                ('manager', models.IntegerField()),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
    ]
